update CI for Gempyre 1.3.6
update artifact name

update CI flow

updated pypi publish script

diff --git a/.github/workflows/scikit-build.yml b/.github/workflows/scikit-build.yml
--- a/.github/workflows/scikit-build.yml
+++ b/.github/workflows/scikit-build.yml
@@ -68,6 +68,19 @@ jobs:
         $env:TEMP = "C:\foo"
         python -m build .
     
+    - name: Install dependencies on ubuntu
+      if: startsWith(matrix.config.name, 'ubuntu')
+      run: |
+        sudo apt-get update
+        sudo apt-get install ninja-build cmake
+        ninja --version
+        make --version
+        gcc --version
+        sudo apt-get install libegl1-mesa
+        sudo apt-get install doxygen
+        sudo apt-get install graphviz
+        sudo apt-get install aspell     
+
     - name: Build 
       if: "!startsWith(matrix.config.name, 'MSVC')"
       run: |
@@ -87,87 +100,72 @@ jobs:
     #    if (NOT result EQUAL 0)
     #      message(FATAL_ERROR "Running tests failed!")
     #    endif()
+
+    - name: Set env
+      shell: bash
+      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV  
     
     - name: Pack
       shell: bash
       run: |
-        cmake -E tar cvzf ${{ matrix.config.artifact }} dist/
+        cmake -E tar cvzf gempyre-py-${{ env.RELEASE_VERSION }}-${{ matrix.config.artifact }} dist/
 
     - name: Upload
       uses: actions/upload-artifact@v3
       with:
-        path: ./${{ matrix.config.artifact }}
-        name: ${{ matrix.config.artifact }}
+        path: ./gempyre-py-${{ env.RELEASE_VERSION }}-${{ matrix.config.artifact }}
+        name: gempyre-py-${{ env.RELEASE_VERSION }}-${{ matrix.config.artifact }}
 
-  release:
-    if: contains(github.ref, 'tags/v')
-    runs-on: ubuntu-latest
-    needs: build
-
-    steps:
-    - name: Create Release
-      id: create_release
-      uses: ncipollo/release-action@v1.12.0
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with:
-        allowUpdates: true
-
-    - name: Store Release url
-      run: |
-        echo "${{ steps.create_release.outputs.upload_url }}" > ./upload_url
-
-    - uses: actions/upload-artifact@v1
-      with:
-        path: ./upload_url
-        name: upload_url
-
+        
   publish:
-    if: contains(github.ref, 'tags/v')
-    name: ${{ matrix.config.name }}
+    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
     runs-on: ${{ matrix.config.os }}
     strategy:
       fail-fast: false
       matrix:
         config:
-        - {
-            name: "Windows Latest MSVC", artifact: "Windows.tar.gz",
-            os: ubuntu-latest
-          }
-        - {
-            name: "Ubuntu Latest GCC", artifact: "Linux.tar.gz",
-            os: ubuntu-latest
-          }
-        - {
-            name: "macOS Latest Clang", artifact: "macOS.tar.gz",
-            os: ubuntu-latest
-          }
-    needs: release
+          - {
+              name: "MSVC",
+              artifact: "Windows.tar.gz",
+              os: windows-latest,
+              build_type: "Release",
+            }
+          - {
+              name: "Ubuntu",
+              artifact: "Linux.tar.gz",
+              os: ubuntu-latest,
+              build_type: "Release"
+            }
+          - {
+              name: "MacOS",
+              artifact: "macOS.tar.gz",
+              os: macos-latest,
+              build_type: "Release"
+            }
+    needs: build
 
     steps:
-    - name: Download artifact
-      uses: actions/download-artifact@v1
-      with:
-        name: ${{ matrix.config.artifact }}
-        path: ./
+      - name: Set env
+        shell: bash
+        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV  
 
-    - name: Download URL
-      uses: actions/download-artifact@v1
-      with:
-        name: upload_url
-        path: ./
-    - id: set_upload_url
-      run: |
-        upload_url=`cat ./upload_url`
-        echo ::set-output name=upload_url::$upload_url
+      - name: Download a Build Artifact
+        uses: actions/download-artifact@v2.1.1
+        with:
+          name:  gempyre-py-${{ env.RELEASE_VERSION }}-${{ matrix.config.artifact }}
 
-    - name: Upload to Release
-      id: upload_to_release
-      uses: actions/upload-release-asset@v1.0.1
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with:
-        upload_url: ${{ steps.set_upload_url.outputs.upload_url }}
-        asset_path: ./${{ matrix.config.artifact }}
-        asset_name: ${{ matrix.config.artifact }}
-        asset_content_type: application/x-gtar
+      - name: Verify version
+        shell: bash
+        run: |
+          REL=$(echo ${{ env.RELEASE_VERSION }} | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')
+          VER=$(tar -tf gempyre-py-${{ env.RELEASE_VERSION }}-${{ matrix.config.artifact }} | grep 'dist/Gempyre-.*-' | cut -d '-' -f 2)
+          if [[ "$REL" != "$VER" ]]; then
+            tar -tf gempyre-py-${{ env.RELEASE_VERSION }}-${{ matrix.config.artifact }} 
+            echo "Invalid version in pyrproject.toml $VER"
+            exit 1
+          fi      
+
+      - name: Release
+        uses: softprops/action-gh-release@v1
+        with:
+          files: gempyre-py-${{ env.RELEASE_VERSION }}-${{ matrix.config.artifact }}
