update CI flow

diff --git a/.github/workflows/scikit-build.yml b/.github/workflows/scikit-build.yml
--- a/.github/workflows/scikit-build.yml
+++ b/.github/workflows/scikit-build.yml
@@ -149,6 +149,15 @@ jobs:
         shell: bash
         run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV  
 
+      - name: Verify version
+        shell: bash
+        run: |
+          VER=$(grep -e '^\s*version\s*=\s*\"' pyproject.toml | cut -d '"' -f 2)
+          if [[ "${{ env.RELEASE_VERSION }}" != "$VER" ]]; then
+            echo "Invalid version in pyrproject.toml $VER"
+            exit 1
+          fi  
+
       - name: Download a Build Artifact
         uses: actions/download-artifact@v2.1.1
         with:
@@ -158,4 +167,3 @@ jobs:
         uses: softprops/action-gh-release@v1
         with:
           files: gempyre-py-${{ env.RELEASE_VERSION }}-${{ matrix.config.artifact }}
-          
